name: Deploy CloudFormation Stack
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Deploy CloudFormation Stack
      uses: aws-actions/aws-cloudformation-deploy@v1
      with:
        stack-name: stack-STD21044
        template: S3.yaml
        capabilities: CAPABILITY_NAMED_IAM
        region: us-east-1
        wait: true
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
